### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by cclauss** [DragonComputer/Dragonfire#43]
Undefined names can raise NameError at runtime

flake8 testing of https://github.com/DragonComputer/Dragonfire on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./dragonfire/timex.py:253:28: F823 local variable 'month' (defined in enclosing scope on line 25) referenced before assignment
		elif re.match(r'last ' + month, timex, re.IGNORECASE):
                           ^

./dragonfire/sr/experimental.py:47:20: F821 undefined name 'p'
			wf.setsampwidth(p.get_sample_size(FORMAT)) # Set sampling format
                   ^

./dragonfire/sr/experimental.py:59:19: F821 undefined name 'p'
		wf.setsampwidth(p.get_sample_size(FORMAT)) # Set sampling format
                  ^

./dragonfire/sr/experimental.py:61:42: F821 undefined name 'frames'
		wf.writeframes(previous_wav + b''.join(frames)) # Write the all frames including previous ones
                                         ^

3     F821 undefined name 'p'
1     F823 local variable 'month' (defined in enclosing scope on line 25) referenced before assignment
```

**Comment by mertyildiran** [comment]
@cclauss one of them is experimental and the other one is not functional but still you can try to fix them. :blush: 

*They are just not in my priorities right now.*

**Comment by mertyildiran** [comment]
@cclauss we integrated Travis CI but now tests are failing because of these issues. Are you planning to fix this issue soon or should I fix it myself? To fix it I think:

 - You should make [month](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/timex.py#L25)'s scope global.
 - Add `p = pyaudio.PyAudio()` before [this line](https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/sr/experimental.py#L44).

**Comment by mertyildiran** [comment]
Fixed with https://github.com/DragonComputer/Dragonfire/commit/49833ab5c456f115da6aa9daf403cdb19c8c905d
