### ISSUE TITLE
Does Dragonfire work on both Python 2 and Python 3?

### ISSUE THREAD

**Issue by cclauss** [DragonComputer/Dragonfire#58]
I would be interested to know which versions of Python people are using when running Dragonfire.  Coding and testing for both versions is work which could be simplified by dropping Python 2 support but that may not yet be an an option.  There are probably performance, asyncio, and f’strings’ reasons for adopting a Python 3 only approach.

**Comment by mertyildiran** [comment]
We are currently distributing Dragonfire by [building a Debian package](https://github.com/DragonComputer/Dragonfire/blob/master/CONTRIBUTING.md#build-the-debian-package)

Python dependencies are listed in [here](https://github.com/DragonComputer/Dragonfire/blob/master/debian/control#L10-L11).

In the future, Python 2.7 will be deprecated and all kind of distros will be migrated to Python 3.x That's why we need to support Python 3.x. Although currently the majority of distros have Python 2.7 support.
