### ISSUE TITLE
dragonfire installed from .deb stays at 100% CPU and very slow

### ISSUE THREAD

**Issue by ianni67** [DragonComputer/Dragonfire#61]
After installing dragonfire from the .deb file, the demo runs very slow, is very unresponsive and the CPU stays at 100% forever.
kde neon last version, Intel I7 CPU, 8GB RAM.

What can I do?

**Comment by mertyildiran** [comment]
@ianni67 the installation process is slow and consumes high amount of CPU resources because it compiles and installs [Kaldi ASR](http://kaldi-asr.org/). This problem(if you think it as a problem) is not directly related to Dragonfire. So please ask to [Kaldi ASR’s maintainers](http://kaldi-asr.org/) for a better alternative than compiling.

**Comment by ianni67** [comment]
I did not complain because installation is slow. I was describing the fact that dragonfire is slow and unresponsive in my computer. I wrote explicitly _after_ the installation. Perhaps I was not clear.
When running dragonfire, it is slow and brings the CPU (Intel I7) up to 100%.
