### ISSUE TITLE
install.sh is asking for the wrong requests version

### ISSUE THREAD

**Issue by Booteille** [DragonComputer/Dragonfire#93]
The `install.sh` script is install requests version `2.19.1` but dragonfire need the version `>=2.20.0`.
A simple `pip install -U requests` fix the issue but I suppose you should update the script.

**Comment by mertyildiran** [comment]
@Booteille oops yeah I forgot to update the installation scripts before pushing [this commit](https://github.com/DragonComputer/Dragonfire/commit/f59624ca5e1be850308525affcc5839ec06d63a7). Since you are the one who first realized this problem, maybe you would like to fix that by sending a pull request?

**Comment by Booteille** [comment]
I have actually not the time to do it. If you can wait some days I'll do it next week. But if you can do it by yourself then just do it.

**Comment by mertyildiran** [comment]
@Booteille besides you should be the one to send the fix in terms of ethics, my purpose here is to increase the number of contributors to this project 😊 

It's actually quite easy; just update the versions of `requests` to `>=2.20.0` in these lines:

1. https://github.com/DragonComputer/Dragonfire/blob/master/install-dev.sh#L57
2. https://github.com/DragonComputer/Dragonfire/blob/master/install.sh#L57
3. https://github.com/DragonComputer/Dragonfire/blob/master/debian/postinst#L35
